final for node

diff --git a/.github/workflows/hi.yml b/.github/workflows/hi.yml
--- a/.github/workflows/hi.yml
+++ b/.github/workflows/hi.yml
@@ -22,4 +22,42 @@ jobs:
         run: npm Install
         working-directory: modules/01.Nodejs_Pipeline
         continue-on-error: false
+        id: install-dependencies
 
+      - name: Run eslint
+        run: npm run lint
+        working-directory: modules/01.Nodejs_Pipeline
+        continue-on-error: false
+        id: run-eslint
+      
+      - name: run jest test
+        run: npm test
+        working-directory: modules/01.Nodejs_Pipeline
+        continue-on-error: false
+        id: run-tests
+
+      - name: check success/failure message
+        if: always()
+        run: |
+            if [ $({ steps.install-dependencies.outcome})=="success"]; then
+            echo: "😃 dependencies installed successfully"
+            else
+              echo "failed to install dependencies"
+              exit 1
+            fi
+           
+            if [ $({ steps.run-eslint.outcome})=="success"]; then
+            echo: "❤️ eslint run successfully"
+            else
+              echo "failed to run eslint"
+              exit 1
+            fi
+
+            if [ $({ steps.run-tests.outcome})=="success"]; then
+            echo: "😇 jest test run successfully"
+            else
+              echo "failed to run jest tests"
+              exit 1
+            fi
+
+            
