hi3

diff --git a/.github/workflows/hi.yml b/.github/workflows/hi.yml
--- a/.github/workflows/hi.yml
+++ b/.github/workflows/hi.yml
@@ -38,25 +38,25 @@ jobs:
       - name: check success/failure message
         if: always()
         run: |
-            if [ $({ steps.install-dependencies.outcome})=="success"]; then
-            echo: "😃 dependencies installed successfully"
+            if [ ${{ steps.install-dependencies.outcome}} =="success"]; then
+                echo: "😃 dependencies installed successfully"
             else
-              echo "failed to install dependencies"
-              exit 1
+                echo "failed to install dependencies"
+                exit 1
             fi
            
-            if [ $({ steps.run-eslint.outcome})=="success"]; then
-            echo: "❤️ eslint run successfully"
+            if [ $({ steps.run-eslint.outcome}) =="success"]; then
+               echo: "❤️ eslint run successfully"
             else
-              echo "failed to run eslint"
-              exit 1
+               echo "failed to run eslint"
+               exit 1
             fi
 
-            if [ $({ steps.run-tests.outcome})=="success"]; then
-            echo: "😇 jest test run successfully"
+            if [ $({ steps.run-tests.outcome}) =="success"]; then
+               echo: "😇 jest test run successfully"
             else
-              echo "failed to run jest tests"
-              exit 1
+               echo "failed to run jest tests"
+               exit 1
             fi
 
             
